### ISSUE TITLE
Usage example not working

### ISSUE THREAD

**Issue by KrAsH-CoD3** [munro/python-selenium-async#2]
Trying the usage example in ReadMe doesn't work. Looking at the documentation seems to help but I can't get started using the Webdriver.

```
print(await selenium_async.run_sync(get_title))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
```

**Comment by cheditx** [comment]
> 

i think you need to learn python before using external libs lol...

you can use await only in Async function, so...

def get_title(driver: selenium_async.WebDriver):
    driver.get("https://google.com")
    return driver.title

async def foo():
    title = await selenium_async.run_sync(get_title))
    print(title)

or just import asyncio and do:

asyncio.run(selenium_async.run_sync(get_title))

**Comment by munro** [comment]
honestly this library kinda sucks, i'm sorry, i've ended up using a modified version of this...  and haven't been doing any scraping lately to circle back
